### ISSUE TITLE
ERROR io.qdb.server.controller.Router

### ISSUE THREAD

**Issue by dec1985** [qdb-io/qdb-server#9]
Here is my timeline of this queue:

[
{
"id": 1,
"timestamp": "2017-12-15T23:01:33.903+0800",
"bytes": "40.96 MB",
"millis": 3081443,
"count": 260949
},
{
"id": 42945475,
"timestamp": "2017-12-15T23:52:55.346+0800",
"bytes": "40.96 MB",
"millis": 608440,
"count": 148951
},
{
"id": 85890967,
"timestamp": "2017-12-16T00:03:03.786+0800",
"bytes": "30.44 MB",
"millis": 458323,
"count": 110241
},
{
"id": 117805810,
"timestamp": "2017-12-16T00:10:42.109+0800",
"bytes": "0 bytes",
"millis": 0,
"count": 0
}
]

When I run this on term:
curl "http://fred2/q/maimai_cn/messages?from=2017-12-15T23:01:33.903+0800&limit=1"
{
  "responseCode" : 500,
  "message" : "Internal server error"}

I've got the errors:

2017-12-16 00:11:30.837 [Dispatcher-4] ERROR io.qdb.server.controller.Router - 500: /q/maimai_cn/messages: java.io.IOException: Checkpoint 42949570 exceeds file size 42913114 [data/queues/default/maimai_cn/0000000000000001-000001605ab1dc4f-260949.qdb]
java.io.IOException: Checkpoint 42949570 exceeds file size 42913114 [data/queues/default/maimai_cn/0000000000000001-000001605ab1dc4f-260949.qdb]
        at io.qdb.buffer.MessageFile.<init>(MessageFile.java:155) ~[qdb-server.jar:0.6.0 2014-12-09 14:22]
        at io.qdb.buffer.MessageFile.<init>(MessageFile.java:106) ~[qdb-server.jar:0.6.0 2014-12-09 14:22]
        at io.qdb.buffer.PersistentMessageBuffer.getMessageFileForCursor(PersistentMessageBuffer.java:637) ~[qdb-server.jar:0.6.0 2014-12-09 14:22]
        at io.qdb.buffer.PersistentMessageBuffer.cursorByTimestamp(PersistentMessageBuffer.java:625) ~[qdb-server.jar:0.6.0 2014-12-09 14:22]
        at io.qdb.server.controller.MessageController.list(MessageController.java:291) ~[qdb-server.jar:0.6.0 2014-12-09 14:22]
        at io.qdb.server.controller.CrudController.handle(CrudController.java:51) ~[qdb-server.jar:0.6.0 2014-12-09 14:22]
        at io.qdb.server.controller.CrudController.handle(CrudController.java:66) ~[qdb-server.jar:0.6.0 2014-12-09 14:22]
        at io.qdb.server.controller.Router.handle(Router.java:73) ~[qdb-server.jar:0.6.0 2014-12-09 14:22]
        at org.simpleframework.http.core.Dispatcher.dispatch(Dispatcher.java:107) [qdb-server.jar:0.6.0 2014-12-09 14:22]
        at org.simpleframework.http.core.Dispatcher.run(Dispatcher.java:90) [qdb-server.jar:0.6.0 2014-12-09 14:22]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by dec1985** [comment]
{
"uptime": "1:22:57",
"qdbVersion": "0.6.0 2014-12-09 14:22",
"heapFreeMemory": "189.09 MB",
"heapMaxMemory": "206 MB",
"otherFreeMemory": "-31368465",
"otherMaxMemory": "-1"
}

Here is my status
